server:
    port: 8081
spring: 
    cloud: 
        config: 
            server: 
                git: 
                    default-label: config
                    uri: https://github.com/victorsigma/Microservicios
                    search-paths: config-data
    application: 
        name: config-service